### PR TITLE
Added contact page with dark light mode

### PR DESCRIPTION
**Pull request by Pallavibahekar**

### CODE REVIEW

**Comment by patelyash5208** [comment]
Please provide screenshot of browser. @Pallavibahekar

**Comment by patelyash5208** [comment]
Thanks for your contribution.
Star the repo . @Pallavibahekar

**Comment by patelyash5208** [comment]
Please connect this page with navbar @Pallavibahekar

**Comment by Pallavibahekar** [comment]
Ok

**Pull request merged**
