### PR TITLE
Added more char cards

### PR DESCRIPTION
**Pull request by Ns-SheF**

### CODE REVIEW

**Comment by patelyash5208** [comment]
Please provide a screenshot of the change you have done. @Ns-SheF

**Comment by Ns-SheF** [comment]
Hi Yash. I think it'll be easier if you compare the pull with the main branch - that way you'll be able to see all changes right? Made some screenshots below tho.

Screenshot 2022-10-06 035851 Duplicate elements.
Screenshot 2022-10-06 040157 New Chars
Screenshot 2022-10-06 040340 Moved styling from .html to css file -there were two <style> elements, so had to erase one...

**Comment by Ns-SheF** [comment]
If you decide to merge this, can you please add the _Hacktoberfest-accepted_ label to it.  It says the repo is not participating. donno why.
Screenshot 2022-10-06 042503

**Comment by patelyash5208** [comment]
> If you decide to merge this, can you please add the _Hacktoberfest-accepted_ label to it. It says the repo is not participating. donno why. Screenshot 2022-10-06 042503

I have already added that tag @Ns-SheF

**Comment by Ns-SheF** [comment]
Yh. sorry bout that. my bad. thanks.

**Pull request merged**
