### PR TITLE
Upload New Got Character Darrio Naharis

### PR DESCRIPTION
**Pull request by raisatwik4**
Upload New GOT character of Darrio Naharis

### CODE REVIEW

**Comment by raisatwik4** [comment]
hackgot

**Comment by patelyash5208** [comment]
Please add more characters more than 3 
And provide output screenshot @raisatwik4

**Comment by patelyash5208** [comment]
Please add 3 or more characters
@raisatwik4  and star the repo

**Comment by raisatwik4** [comment]
Thank you,
          for seen my repo. I try my best to make this repo best.

**Comment by raisatwik4** [comment]
Update 3 GOT character Successfullty.
My screenshot link that change i made
-> https://i.postimg.cc/s2dzZVzv/hacktobergot.png

**Comment by patelyash5208** [comment]
You have to provide what ever browser output . @raisatwik4

**Comment by raisatwik4** [comment]
> Output of GOT character that added by me

outputGOT

**Comment by raisatwik4** [comment]
OUTPUT
outputGOT

**Comment by raisatwik4** [comment]
Thank you!

**Pull request merged**
