### PR TITLE
added hovering effect

### PR DESCRIPTION
**Pull request by chharikha2003**
On  selecting a particular icon of the navigation bar the color will change to grey

### CODE REVIEW

**Comment by chharikha2003** [comment]
Can you please check and tell if something else should also be done

**Comment by chharikha2003** [comment]
Modified the navigation bar according to the description given.Please tell if something is missing

**Comment by chharikha2003** [comment]
WhatsApp Image 2022-10-13 at 11 53 47
WhatsApp Image 2022-10-13 at 11 53 09

**Comment by chharikha2003** [comment]
Can you please add the lable of hactoberfest accepted as well

**Comment by patelyash5208** [comment]
sorry for not doing that.
Please star the repo.

**Pull request merged**
